// Generated by gencpp from file HMCL_V2X/HMCL_SPATdata.msg
// DO NOT EDIT!


#ifndef HMCL_V2X_MESSAGE_HMCL_SPATDATA_H
#define HMCL_V2X_MESSAGE_HMCL_SPATDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace HMCL_V2X
{
template <class ContainerAllocator>
struct HMCL_SPATdata_
{
  typedef HMCL_SPATdata_<ContainerAllocator> Type;

  HMCL_SPATdata_()
    : states(0)
    , movementName()
    , signalGroup(0)
    , eventState(0)
    , timing_min_End_Time(0)
    , connectionID(0)
    , pedBicycleDetect(false)  {
    }
  HMCL_SPATdata_(const ContainerAllocator& _alloc)
    : states(0)
    , movementName(_alloc)
    , signalGroup(0)
    , eventState(0)
    , timing_min_End_Time(0)
    , connectionID(0)
    , pedBicycleDetect(false)  {
  (void)_alloc;
    }



   typedef int32_t _states_type;
  _states_type states;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _movementName_type;
  _movementName_type movementName;

   typedef int32_t _signalGroup_type;
  _signalGroup_type signalGroup;

   typedef int32_t _eventState_type;
  _eventState_type eventState;

   typedef int32_t _timing_min_End_Time_type;
  _timing_min_End_Time_type timing_min_End_Time;

   typedef int32_t _connectionID_type;
  _connectionID_type connectionID;

   typedef uint8_t _pedBicycleDetect_type;
  _pedBicycleDetect_type pedBicycleDetect;





  typedef boost::shared_ptr< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> const> ConstPtr;

}; // struct HMCL_SPATdata_

typedef ::HMCL_V2X::HMCL_SPATdata_<std::allocator<void> > HMCL_SPATdata;

typedef boost::shared_ptr< ::HMCL_V2X::HMCL_SPATdata > HMCL_SPATdataPtr;
typedef boost::shared_ptr< ::HMCL_V2X::HMCL_SPATdata const> HMCL_SPATdataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator1> & lhs, const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator2> & rhs)
{
  return lhs.states == rhs.states &&
    lhs.movementName == rhs.movementName &&
    lhs.signalGroup == rhs.signalGroup &&
    lhs.eventState == rhs.eventState &&
    lhs.timing_min_End_Time == rhs.timing_min_End_Time &&
    lhs.connectionID == rhs.connectionID &&
    lhs.pedBicycleDetect == rhs.pedBicycleDetect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator1> & lhs, const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace HMCL_V2X

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3135b1ac657326c96fd84764b8da054d";
  }

  static const char* value(const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3135b1ac657326c9ULL;
  static const uint64_t static_value2 = 0x6fd84764b8da054dULL;
};

template<class ContainerAllocator>
struct DataType< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HMCL_V2X/HMCL_SPATdata";
  }

  static const char* value(const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 states\n"
"string movementName\n"
"int32 signalGroup\n"
"int32 eventState\n"
"int32 timing_min_End_Time\n"
"int32 connectionID\n"
"bool pedBicycleDetect\n"
"\n"
;
  }

  static const char* value(const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.states);
      stream.next(m.movementName);
      stream.next(m.signalGroup);
      stream.next(m.eventState);
      stream.next(m.timing_min_End_Time);
      stream.next(m.connectionID);
      stream.next(m.pedBicycleDetect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HMCL_SPATdata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HMCL_V2X::HMCL_SPATdata_<ContainerAllocator>& v)
  {
    s << indent << "states: ";
    Printer<int32_t>::stream(s, indent + "  ", v.states);
    s << indent << "movementName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.movementName);
    s << indent << "signalGroup: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signalGroup);
    s << indent << "eventState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.eventState);
    s << indent << "timing_min_End_Time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timing_min_End_Time);
    s << indent << "connectionID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.connectionID);
    s << indent << "pedBicycleDetect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pedBicycleDetect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HMCL_V2X_MESSAGE_HMCL_SPATDATA_H
