(cl:in-package HMCL_V2X-msg)
(cl:export '(NAME-VAL
          NAME
          REGION-VAL
          REGION
          ID-VAL
          ID
          REVISION-VAL
          REVISION
          STATUS-VAL
          STATUS
          MOY-VAL
          MOY
          TIMESTAMP-VAL
          TIMESTAMP
          STATES-VAL
          STATES
          MOVEMENTNAME-VAL
          MOVEMENTNAME
          SIGNALGROUP-VAL
          SIGNALGROUP
          EVENTSTATE-VAL
          EVENTSTATE
          TIMING_MIN_END_TIME-VAL
          TIMING_MIN_END_TIME
          CONNECTIONID-VAL
          CONNECTIONID
          PEDBICYCLEDETECT-VAL
          PEDBICYCLEDETECT
))